@extends('layout.app')
@section('content')
    @include('components.MenuBar')
    @include('components.HeroSlider')
    @include('components.TopCategories')
    @include('components.ExclusiveProducts')
    @include('components.TopBrands')
    @include('components.Footer')
@endsection
